---
spring:
  application:
    name: spring-boot-demo-app

logging:
  level:
    com.example: DEBUG

hello:
  greeting: Bonjour

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: mappings,beans

---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/todos?autoReconnect=true&useSSL=false
    username: todo_user
    password: secret
  jpa:
    generate-ddl: true

